name: Deploy varn.agency
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ secrets.SSH_HOST }}
  DEPLOY_USER: ${{ secrets.SSH_USER }}
  DEPLOY_PATH: /srv/www/varn.agency/current/public
  SRC_DIR: ./public   # change to ./dist or ./ if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - run: npm ci && npm run build   # if you build; then set SRC_DIR=./dist

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            printf "%s\n" "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          else
            ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          fi

      - name: Deploy via rsync
        run: |
          rsync -az --delete \
            --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
            "$SRC_DIR"/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Reload Nginx
        run: ssh "$DEPLOY_USER@$DEPLOY_HOST" 'sudo systemctl reload nginx || true'
