name: Deploy varn.agency
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ secrets.SSH_HOST }}
  DEPLOY_USER: ${{ secrets.SSH_USER }}
  DEPLOY_PATH: /srv/www/varn.agency/current/public
  SRC_DIR: ./public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assert secrets exist (fail fast with a clear message)
        run: |
          set -e
          [ -n "${{ secrets.SSH_HOST }}" ] || { echo "Missing secret: SSH_HOST"; exit 2; }
          [ -n "${{ secrets.SSH_USER }}" ] || { echo "Missing secret: SSH_USER"; exit 2; }
          [ -n "${{ secrets.SSH_KEY }}" ]  || { echo "Missing secret: SSH_KEY (must be FULL PRIVATE KEY, not a fingerprint)"; exit 2; }
          [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ] || { echo "Missing secret: SSH_KNOWN_HOSTS"; exit 2; }

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Write known_hosts
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Smoke test SSH
        run: |
          ssh -o StrictHostKeyChecking=yes "$DEPLOY_USER@$DEPLOY_HOST" 'echo SSH_OK && id && ls -ld /srv/www/varn.agency/current/public || true'

      - name: Debug: list SRC_DIR
        run: |
          echo "SRC_DIR=$SRC_DIR"
          ls -lah "$SRC_DIR"

      - name: Ensure target dir exists
        run: ssh "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p '$DEPLOY_PATH'"

      - name: Deploy via rsync (verbose)
        run: |
          rsync -azv --delete \
            "$SRC_DIR"/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Write deploy marker & reload
        run: |
          printf '{"commit":"%s","time":"%s"}' "${GITHUB_SHA}" "$(date -u +%FT%TZ)" \
           | ssh "$DEPLOY_USER@$DEPLOY_HOST" "cat > '$DEPLOY_PATH/__health.json'"
          ssh "$DEPLOY_USER@$DEPLOY_HOST" 'sudo systemctl reload nginx || true'
