name: Deploy varn.agency
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ secrets.SSH_HOST }}
  DEPLOY_USER: ${{ secrets.SSH_USER }}
  DEPLOY_PATH: /srv/www/varn.agency/current/public
  SRC_DIR: ./public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Write known_hosts
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Debug: list SRC_DIR
        run: |
          echo "SRC_DIR=$SRC_DIR"
          ls -lah "$SRC_DIR"

      - name: Ensure target dir exists
        run: ssh "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p '$DEPLOY_PATH'"

      - name: Deploy via rsync (verbose)
        run: |
          rsync -azv --delete \
            "$SRC_DIR"/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Write deploy marker & reload
        run: |
          TS="$(date -u +%FT%TZ)"
          echo "{\"commit\":\"${GITHUB_SHA}\",\"time\":\"${TS}\"}" > health.json
          scp health.json "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/__health.json"
          ssh "$DEPLOY_USER@$DEPLOY_HOST" 'sudo systemctl reload nginx || true'
