name: Deploy varn.agency
on:
  push: { branches: [ main ] }
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ secrets.SSH_HOST }}
  DEPLOY_USER: ${{ secrets.SSH_USER }}
  DEPLOY_PATH: /srv/www/varn.agency/current/public
  SRC_DIR: ./public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug: list SRC_DIR
        run: |
          echo "SRC_DIR=$SRC_DIR"
          ls -lah "$SRC_DIR" || { echo "SRC_DIR missing"; exit 2; }

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -azv --delete \
            "$SRC_DIR"/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Write deploy marker
        run: |
          printf '{"commit":"%s","time":"%s"}' "${GITHUB_SHA}" "$(date -u +%FT%TZ)" \
          | ssh "$DEPLOY_USER@$DEPLOY_HOST" "cat > '$DEPLOY_PATH/__health.json'"
          ssh "$DEPLOY_USER@$DEPLOY_HOST" 'sudo systemctl reload nginx || true'
